
---
resources:
  - name: work-image
    type: registry-image
    source:
      repository: tiwafuchi/ubuntu-tanzu
  - name: resource-tanzu
    type: git
    source:
      uri: https://github.com/amagaeru/tanzu-demo.git

jobs:
  - name: job-create-cluster
    public: true
    plan:
      - get: resource-tanzu
        trigger: true
      - get: work-image
      - task: create-cluster
        file: resource-tanzu/pipeline-create-cluster/01-create-cluster-task.yaml
        image: work-image
  - name: job-deploy-monitor
    public: true
    plan:
    - get: work-image
      passed: [job-create-cluster]
    - get: resource-tanzu
      passed: [job-create-cluster]
      trigger: true
    - task: deploy-monitor
      file: resource-tanzu/pipeline-create-cluster/02-deploy-monitor-task.yaml
      image: work-image
  - name: job-deploy-logs
    public: true
    plan:
    - get: work-image
      passed: [job-deploy-monitor]
    - get: resource-tanzu
      passed: [job-deploy-monitor]
      trigger: true
    - task: deploy-logs
      file: resource-tanzu/pipeline-create-cluster/03-deploy-logs-task.ymaml
      image: work-image
  - name: job-deploy-velero
    public: true
    plan:
    - get: work-image
      passed: [job-deploy-logs]
    - get: resource-tanzu
      passed: [job-deploy-logs]
      trigger: true
    - task: deploy-velero
      file: resource-tanzu/pipelinecreatecluster/04-deploy-velero-task.yaml
      image: work-image
