apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: w03dev01-tkg10
  namespace: w03dev01
spec:
  distribution:
    fullVersion: null
    version: v1.17.8
  topology:
    controlPlane:
      count: 1
      class: best-effort-xsmall
      storageClass: vsan-default-storage-policy
    workers:
      count: 5
      class: best-effort-xsmall
      storageClass: vsan-default-storage-policy
  settings:
    storage:
      defaultClass: vsan-default-storage-policy